export const USERS =[
    {
        id:1,
        firstName:"rutu",
        lastName:"patel",
        emailAddress:"abc@gmail.com",
        dOB: new Date("2023-05-07"),
        gender: "Female",
        password: "Rutu1234",
        cPassword: "Rutu1234",
    },
    {
        id:2,
        firstName:"test",
        lastName:"test",
        emailAddress:"rutu@gmail.com",
        dOB: new Date("01-12-2001"), 
        gender: "Male",
        password: "Test7834",
        cPassword: "Test7834",
    },
    {
        id:3,
        firstName:"abc",
        lastName:"def",
        emailAddress:"test@gmail.com",
        dOB: new Date("03-08-2020"), 
        gender: "Female",
        password: "4Asgkc52",
        cPassword: "4Asgkc52",
    },
    {
        id:4,
        firstName:"john",
        lastName:"jkl",
        emailAddress:"xyzw@gmail.com",
        dOB: new Date("04-02-2018"), 
        gender: "Male",
        password: "John5092",
        cPassword: "John5092",
    },
    {
        id:5,
        firstName:"mary",
        lastName:"jons",
        emailAddress:"jons@gmail.com",
        dOB: new Date("12-04-2002"), 
        gender: "Female",
        password: "10Jons12",
        cPassword: "10Jons12",
    },
    {
        id:6,
        firstName:"xyz",
        lastName:"efg",
        emailAddress:"hjk@yahoo.com",
        dOB: new Date("04-07-2019"), 
        gender: "Male",
        password: "9xyzW163",
        cPassword: "9xyzW163",
    }
]
