export const USERS =[
    {
        id:1,
        firstName:"rutu",
        lastName:"patel",
        emailAddress:"abc@gmail.com",
        dOB: "05-07-2023",
        gender: "Female",
        password: "Rutu1234",
        cPassword: "Rutu1234",
    },
    {
        id:2,
        firstName:"test",
        lastName:"test",
        emailAddress:"rutu@gmail.com",
        dOB: "01-12-2001",
        gender: "Male",
        password: "Test1234",
        cPassword: "Test1234",
    },
    {
        id:3,
        firstName:"abc",
        lastName:"def",
        emailAddress:"test@gmail.com",
        dOB: "03-08-2020",
        gender: "Female",
        password: "Abc12345",
        cPassword: "Abc12345",
    },
    {
        id:4,
        firstName:"john",
        lastName:"def",
        emailAddress:"xyzw@gmail.com",
        dOB: "04-02-2018",
        gender: "Male",
        password: "John1712",
        cPassword: "John1712",
    },
    {
        id:5,
        firstName:"mary",
        lastName:"jons",
        emailAddress:"jons@gmail.com",
        dOB: "12-04-2002",
        gender: "Female",
        password: "14Jons12",
        cPassword: "14Jons12",
    },
    {
        id:6,
        firstName:"xyz",
        lastName:"efg",
        emailAddress:"hjk@yahoo.com",
        dOB: "04-07-2019",
        gender: "Male",
        password: "1xyzW123",
        cPassword: "1xyzW123",
    }
]
